"""Beava Python SDK.

Public surface: ``bv.event`` / ``bv.table`` / ``bv.col`` / ``bv.lit`` /
``bv.App`` plus the operator catalogue. v0 ships events-only per the locked
``project_v0_events_only_scope`` commitment (ADR-001 partial overturn revives
``@bv.table`` for aggregation-output only — no ``upsert`` / ``delete`` /
``retract`` paths).
"""

from __future__ import annotations

from beava._agg import (  # noqa: F401
    age,
    avg,
    bloom_member,
    burst_count,
    count,
    count_distinct,
    decayed_count,
    decayed_sum,
    delta_from_prev,
    distance_from_home,
    dow_hour_histogram,
    ema,
    entropy,
    event_type_mix,
    ew_zscore,
    ewma,
    ewvar,
    first,
    first_n,
    first_seen,
    first_seen_in_window,
    geo_distance,
    geo_spread,
    geo_velocity,
    has_seen,
    histogram,
    hour_of_day_histogram,
    inter_arrival_stats,
    lag,
    last,
    last_n,
    last_seen,
    max,
    max_streak,
    mean,
    min,
    most_recent_n,
    n_unique,
    negative_streak,
    outlier_count,
    percentile,
    quantile,
    rate_of_change,
    ratio,
    reservoir_sample,
    seasonal_deviation,
    std,
    stddev,
    streak,
    sum,
    time_since,
    time_since_last_n,
    top_k,
    trend,
    trend_residual,
    twa,
    value_change_count,
    var,
    variance,
    z_score,
)
from beava._app import App  # noqa: F401
from beava._col import (  # noqa: F401
    clip,
    col,
    hash_mod,
    hour_of_day,
    if_else,
    length,
    lit,
    log1p,
)
from beava._demo import demo  # noqa: F401
from beava._errors import (  # noqa: F401
    BinaryNotFoundError,
    RegistrationError,
    ValidationError,
)
from beava._events import event  # noqa: F401
from beava._table import table  # noqa: F401

__all__ = [
    "App",
    "RegistrationError",
    "BinaryNotFoundError",
    "ValidationError",
    "col",
    "lit",
    "event",
    "table",
    "demo",
    "count",
    "sum",
    "mean",
    "min",
    "max",
    "var",
    "std",
    "ratio",
    "n_unique",
    "quantile",
    "top_k",
    "bloom_member",
    "entropy",
    "first",
    "last",
    "first_n",
    "last_n",
    "lag",
    "first_seen",
    "last_seen",
    "age",
    "has_seen",
    "time_since",
    "time_since_last_n",
    "streak",
    "max_streak",
    "negative_streak",
    "first_seen_in_window",
    "ewma",
    "ema",
    "ewvar",
    "ew_zscore",
    "decayed_sum",
    "decayed_count",
    "twa",
    "rate_of_change",
    "inter_arrival_stats",
    "burst_count",
    "delta_from_prev",
    "trend",
    "trend_residual",
    "outlier_count",
    "value_change_count",
    "z_score",
    "histogram",
    "hour_of_day_histogram",
    "dow_hour_histogram",
    "seasonal_deviation",
    "event_type_mix",
    "most_recent_n",
    "reservoir_sample",
    "geo_velocity",
    "geo_distance",
    "geo_spread",
    "distance_from_home",
    "avg",
    "variance",
    "stddev",
    "count_distinct",
    "percentile",
    "log1p",
    "clip",
    "hour_of_day",
    "hash_mod",
    "length",
    "if_else",
]
